### ISSUE TITLE
Prefabs does not have any mesh attached to it

### ISSUE THREAD

**Issue by LordRaccoon** [Seanba/Tiled2Unity#122] opened 2017-08-15 19:18 UTC
I guess I'm just noobing, but I cannot manage to import my map to Unity.
It load the prefab just like a blue cube (meshes are not imported somehow)
here is the picture of the preview:
![image](https://user-images.githubusercontent.com/13445310/29331955-49a5242e-81cc-11e7-8d61-bb76340bf5f9.png)

Here is the picture of the prefab:
![image](https://user-images.githubusercontent.com/13445310/29332043-a052ea90-81cc-11e7-8c83-c621e025ef40.png)

Here is the meshes inside unity
![image](https://user-images.githubusercontent.com/13445310/29332071-ba3a78f6-81cc-11e7-8988-04b8ef3f137e.png)

here are the errors:
![image](https://user-images.githubusercontent.com/13445310/29332097-d1c5f7de-81cc-11e7-92f0-4b0353c38395.png)

That's is what shows on my scene:
![image](https://user-images.githubusercontent.com/13445310/29332151-048e29ac-81cd-11e7-8c1e-0a46014e420d.png)

**Comment by Seanba** [comment] 2017-08-17 18:17
Are you using Unity 5.2 by chance? When adding backwards compatibility for Unity 4.7 it looks like I broke BC for early versions of Unity 5.x.

**Comment by LordRaccoon** [comment] 2017-08-17 18:24
I searched for the version and all that says is Unity 2017.1 and that looks like is the newest version after 5.6.3
Thank you for taking the time to help me with that.

**Comment by Seanba** [comment] 2017-08-17 19:55
Unity 2017 should be fine. I wonder if the problem is more because your map is named `1.1` and either Unity or my Tiled2Unity import scripts get choked up on that. Can you send me your exported `1.1.tiled2unity.xml` file? You can find my email at www.seanba.com

**Comment by Seanba** [comment] 2017-08-18 23:36
FTR, this is a bug in the Tiled2Unity scripts if you have a map name with a period in it (ie. '`my.map.tmx`'). I will post an update soon.

**Comment by LordRaccoon** [comment] 2017-08-18 23:42
Thank you for your prompt answer! It really work very well using names. You are great! thanks for all the time and effort you put on Tiled2Unity!

**Comment by Seanba** [comment] 2017-08-28 05:02
Version 1.0.12.4 has the fix for this published. Thanks again for bringing it to my attention.

**Closed by Seanba** 2017-08-28 05:02 UTC
