### ISSUE TITLE
Tiled Object Collider Types -> Unity Layer. Always "Default"

### ISSUE THREAD

**Issue by steveadoo32** [Seanba/Tiled2Unity#102] opened 2017-05-25 14:47 UTC
Hi,

This is more of a question(could be a bug, not sure). 

So I've got an Objects layer inside Tiled, and I'm adding images to it with colliders defined on them. The colliders have their Type property set to "Obstacle". When I import into Unity though, the objects with colliders in Unity aren't on the Obstacle layer, they're on the Default layer.

If I add these images to a Tile layer, the layers are set correctly inside Unity.

I've found the code where it assigns layers to tile images on objects [here](https://github.com/Seanba/Tiled2Unity/blob/master/tool/Tiled2Unity/Tiled2UnityLib/ExportClasses/TiledMapExporter.Prefab.cs#L643)

So it looks like I need an Object type on my map that matches "Obstacle", otherwise it's going to just use "Default" as the Unity layer. Is that behavior correct? I would think that it'd just assign that collider object's Unity layer to whatever the "Type" property is, like it does for images on tile layers.

**Comment by Seanba** [comment] 2017-05-28 23:01
Hi Steveadoo32, the expectation is that your TileObject will be on the Default layer but will have game object children that have collisions on them with the proper layer applied. This is because a tile can have collisions of multiple types on it, so it needs to be broken down.

Are you seeing something different?

**Comment by steveadoo32** [comment] 2017-05-28 23:04
Hi, 

The layers for the Collison object is not on the layer I define in the type field in the Tiled collision editor window. 

It's always on the Default layer.

**Comment by Seanba** [comment] 2017-05-28 23:27
If you send me your exported tiled2unity.xml file I can check that out quickly as a start. Thanks.

**Comment by Seanba** [comment] 2017-10-08 05:29
Lacking additional information I will close this issue for now. Feel free to re-open if you think there is a bug here that I can reproduce.

**Comment by indspenceable** [comment] 2017-11-26 22:29
Hi -

I'm running into the same issue here. I've got a tile that is set up correctly for collisions, but it always ends up only having collisions on the Default layer (it does get a `Collision_Default` child game object).

I've set the `Type` on the tile correctly, so when I just place the tile on a normal tile layer, the collisions work as expected; also if I make a rectangular object, it works as expected. When I try to add that tile with a TileObject, even if I add set the `Type` on the tileobject itself, and I use a tile that has an object w/ a set type, it always only collides on the default layer.

Hope that helps diagnose it! Thank you for your great tool, it's very helpful :)

**Comment by indspenceable** [comment] 2017-11-26 22:43
Also - I've looked through my .tiled2unity.xml and it looks like the layer is already Default at that point (see https://gist.github.com/indspenceable/d69503a1e1f6e68a927dfbd937e55ca2) so that leads me to believe that maybe I'm missing a layer setting somewhere? If so it might be intuitive to make that more in line with how you set the collision layer for other objects.... but just speculating here.

**Comment by Seanba** [comment] 2017-11-27 16:42
Hi Daniel, do you have a small example I can try to export? You can find my email address from my blog: www.seanba.com

I'll need the TMX file and any tileset data (TSX and textures). Thanks.

**Comment by indspenceable** [comment] 2017-12-03 15:00
Hey - I sent an email with an example a few days ago. Let me know if you didn't receive it!

**Comment by indspenceable** [comment] 2017-12-03 17:17
Welp, it looks like I got mixed up - using the "unity:layer" does indeed set the layer correctly. Working as intended, this issue should be closed. Thank you!!

**Comment by Seanba** [comment] 2017-12-17 16:36
I did a bit of work on this for Tiled2Unity 1.0.13.2, just released now, which does a better job of collecting like-colliders and putting them in a layer appropriately named.

**Closed by Seanba** 2017-12-17 16:36 UTC
