### ISSUE TITLE
Unknown problem - importing tile map

### ISSUE THREAD

**Issue by JoshElgar** [Seanba/Tiled2Unity#101] opened 2017-05-23 21:43 UTC
![image](https://cloud.githubusercontent.com/assets/7473757/26377593/d4c26194-4008-11e7-8672-b42389750ba4.png)

The above is the output from Tiled2Unity after clicking the big ass export button. Below are the errors I received in Unity upon importing.

![image](https://cloud.githubusercontent.com/assets/7473757/26377645/0457e168-4009-11e7-9d14-6b46c54b510d.png)

The map looks strange when placed and in the project view, only having the base outline:

![image](https://cloud.githubusercontent.com/assets/7473757/26377675/28889640-4009-11e7-85e8-5a955c88614d.png)

Am I doing something wrong?

**Comment by Seanba** [comment] 2017-05-23 21:58
That polygon path warning is an indication to you that your colliders are not being merged into a (much) smaller number of polygon paths. I suspect that is because of the way you've created colliders on your tiles in the Tiled Collision Editor. It is must commonly caused when you are not using grid-snapping.

The other error is much more serious. Can you send me your exported map1.tiled2unity.xml file?

**Comment by JoshElgar** [comment] 2017-05-24 08:53
Sure, sorry for taking a while, posted this when I went to bed. I couldn't attach the XML file because Github doesn't support it apparently, so I just zipped it, hopefully that works.

[map1.tiled2unity.xml.zip](https://github.com/Seanba/Tiled2Unity/files/1024917/map1.tiled2unity.xml.zip)

**Comment by JoshElgar** [comment] 2017-05-24 09:04
Update: Just fixed the colliders :) Exports perfectly, no errors. Cheers!

**Comment by Seanba** [comment] 2017-05-24 15:19
The problem is with your texture name: `32x32_map_tile v3.1.png`

It has both a whitespace and an extra period so the Tiled2Unity scripts are getting confused trying to find the material asset after it is imported. I'll fix the scripts to handle this case but in the meantime if you name your texture something a bit "friendlier" like `32x32_map_tile_v3_1.png` then you'll get things working.

**Comment by JoshElgar** [comment] 2017-05-24 15:31
Thank you very much!

**Comment by Seanba** [comment] 2017-05-24 16:04
Thanks, Josh, glad it's working for you. However, I'm going to keep this open until I release a version of Tiled2Unity that handles material names a bit better. Should be just a couple of days.

**Comment by Seanba** [comment] 2017-06-08 00:39
Tiled2Unity 1.0.12.1 contains the fix for this. Thanks again for the bug report.

**Closed by Seanba** 2017-06-08 00:39 UTC
